// <auto-generated />
using System;
using GenericApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260621232626_AddContractSigns")]
    partial class AddContractSigns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GenericApp.Data.Models.ApplicationLog", b =>
                {
                    b.Property<int>("IdApplicationLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApplicationLog"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Details2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDataAffected")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdApplicationLog");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("GenericApp.Data.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdState")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdCity");

                    b.HasIndex("IdState");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            IdCity = 1,
                            Description = "Tijuana",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 2,
                            Description = "Mexicali",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 3,
                            Description = "Ensenada",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 4,
                            Description = "Playas de Rosarito",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 5,
                            Description = "Tecate",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 6,
                            Description = "San Quintín",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 7,
                            Description = "San Felipe",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 8,
                            Description = "Los Angeles",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 9,
                            Description = "San Diego",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 10,
                            Description = "San Jose",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 11,
                            Description = "Calexico",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdClient");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdCompany");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Empaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GnnNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegFdaNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdCompany");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            IdCompany = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mision"
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Contract", b =>
                {
                    b.Property<int>("IdContract")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContract"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VirtualPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdContract");

                    b.HasIndex("IdCompany");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ContractSign", b =>
                {
                    b.Property<int>("IdContractSign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContractSign"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SignFileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdContractSign");

                    b.ToTable("ContractSigns");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ContractTemplate", b =>
                {
                    b.Property<int>("IdTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTemplate"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsHeaderEnable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdTemplate");

                    b.HasIndex("IdCompany");

                    b.ToTable("ContractTemplates");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ContractTemplateContractSign", b =>
                {
                    b.Property<int>("IdContractTemplateContractSign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContractTemplateContractSign"), 1L, 1);

                    b.Property<int>("IdContractSign")
                        .HasColumnType("int");

                    b.Property<int>("IdContractTemplate")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdContractTemplateContractSign");

                    b.HasIndex("IdContractSign");

                    b.HasIndex("IdContractTemplate");

                    b.ToTable("ContractTemplateContractSigns");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ContractTemplateVariable", b =>
                {
                    b.Property<int>("IdContractTemplateVariable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContractTemplateVariable"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContractTemplateVariable");

                    b.ToTable("ContractTemplateVariables");

                    b.HasData(
                        new
                        {
                            IdContractTemplateVariable = 1,
                            Code = "nombreEmpresa",
                            Description = "Nombre de la empresa",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 2,
                            Code = "fechaActualContrato",
                            Description = "Fecha actual contrato",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 3,
                            Code = "clave",
                            Description = "Clave",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 4,
                            Code = "nombre",
                            Description = "Nombre",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 5,
                            Code = "nacionalidad",
                            Description = "Nacionalidad",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 6,
                            Code = "edad",
                            Description = "Edad",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "int"
                        },
                        new
                        {
                            IdContractTemplateVariable = 7,
                            Code = "sexo",
                            Description = "Sexo",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 8,
                            Code = "estadoCivil",
                            Description = "Estado Civil",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 9,
                            Code = "curp",
                            Description = "CURP",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 10,
                            Code = "rfc",
                            Description = "RFC",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 11,
                            Code = "numeroAfiliacionImss",
                            Description = "Número de Afiliación IMSS",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 12,
                            Code = "domicilio",
                            Description = "Domicilio",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 13,
                            Code = "puesto",
                            Description = "Puesto",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 14,
                            Code = "turno",
                            Description = "Turno",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 15,
                            Code = "salarioDiarioBase",
                            Description = "Salario Diario Base",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "decimal"
                        },
                        new
                        {
                            IdContractTemplateVariable = 16,
                            Code = "fechaInicioContrato",
                            Description = "Fecha de Inicio del Contrato",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 17,
                            Code = "fechaTerminacionContrato",
                            Description = "Fecha de Terminación del Contrato",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 18,
                            Code = "fechaActualFormatoCorto",
                            Description = "Fecha Actual Formato Corto",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 19,
                            Code = "fechaActualFormatoLargo",
                            Description = "Fecha Actual Formato Largo",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 20,
                            Code = "firmaContrato",
                            Description = "Firma del Contrato",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 21,
                            Code = "Beneficiario1",
                            Description = "Beneficiario 1",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 22,
                            Code = "Beneficiario1_Domicilio",
                            Description = "Domicilio del Beneficiario 1",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 23,
                            Code = "Beneficiario1_FechaNacimiento",
                            Description = "Fecha de Nacimiento del Beneficiario 1",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 24,
                            Code = "Beneficiario1_Telefono",
                            Description = "Teléfono del Beneficiario 1",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 25,
                            Code = "Beneficiario1_Porcentaje",
                            Description = "Porcentaje del Beneficiario 1",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 26,
                            Code = "Beneficiario2",
                            Description = "Beneficiario 2",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 27,
                            Code = "Beneficiario2_Domicilio",
                            Description = "Domicilio del Beneficiario 2",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 28,
                            Code = "Beneficiario2_FechaNacimiento",
                            Description = "Fecha de Nacimiento del Beneficiario 2",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 29,
                            Code = "Beneficiario2_Telefono",
                            Description = "Teléfono del Beneficiario 2",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 30,
                            Code = "Beneficiario2_Porcentaje",
                            Description = "Porcentaje del Beneficiario 2",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 31,
                            Code = "Beneficiario3",
                            Description = "Beneficiario 3",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 32,
                            Code = "Beneficiario3_Domicilio",
                            Description = "Domicilio del Beneficiario 3",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 33,
                            Code = "Beneficiario3_FechaNacimiento",
                            Description = "Fecha de Nacimiento del Beneficiario 3",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 34,
                            Code = "Beneficiario3_Telefono",
                            Description = "Teléfono del Beneficiario 3",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 35,
                            Code = "Beneficiario3_Porcentaje",
                            Description = "Porcentaje del Beneficiario 3",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 36,
                            Code = "Beneficiario4",
                            Description = "Beneficiario 4",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 37,
                            Code = "Beneficiario4_Domicilio",
                            Description = "Domicilio del Beneficiario 4",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 38,
                            Code = "Beneficiario4_FechaNacimiento",
                            Description = "Fecha de Nacimiento del Beneficiario 4",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "DateTime"
                        },
                        new
                        {
                            IdContractTemplateVariable = 39,
                            Code = "Beneficiario4_Telefono",
                            Description = "Teléfono del Beneficiario 4",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        },
                        new
                        {
                            IdContractTemplateVariable = 40,
                            Code = "Beneficiario4_Porcentaje",
                            Description = "Porcentaje del Beneficiario 4",
                            IsActive = true,
                            IsDeleted = false,
                            Type = "string"
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCountry"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdCountry");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            IdCountry = 1,
                            Description = "México",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCountry = 2,
                            Description = "Estados Unidos",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CURP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CivilStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Clave")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IMSS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RFC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdCompany");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeBeneficiarie", b =>
                {
                    b.Property<int>("IdEmployeeBeneficiarie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployeeBeneficiarie"), 1L, 1);

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployeeRelationshipType")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdEmployeeBeneficiarie");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdEmployeeRelationshipType");

                    b.ToTable("EmployeeBeneficiaries");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeDependents", b =>
                {
                    b.Property<int>("IdEmployeeDependents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployeeDependents"), 1L, 1);

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployeeRelationshipType")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("IdEmployeeDependents");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdEmployeeRelationshipType");

                    b.ToTable("EmployeeDependents");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeEmergencyContact", b =>
                {
                    b.Property<int>("IdEmployeeEmergencyContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployeeEmergencyContact"), 1L, 1);

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployeeRelationshipType")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdEmployeeEmergencyContact");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdEmployeeRelationshipType");

                    b.ToTable("EmployeeEmergencyContacts");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeRelationshipType", b =>
                {
                    b.Property<int>("IdEmployeeRelationshipType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployeeRelationshipType"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdEmployeeRelationshipType");

                    b.ToTable("EmployeeRelationshipTypes");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeWorkInformation", b =>
                {
                    b.Property<int>("IdEmployeeWorkInformation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployeeWorkInformation"), 1L, 1);

                    b.Property<DateTime>("ContractExpiration")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IntegralSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PayType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmployeeWorkInformation");

                    b.HasIndex("IdEmployee");

                    b.ToTable("EmployeeWorkInformations");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Parameter", b =>
                {
                    b.Property<int>("IdParameter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParameter"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdParameter");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("GenericApp.Data.Models.RefreshTokenAspNetUser", b =>
                {
                    b.Property<int>("IdRefreshTokenAspNetUser")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefreshTokenAspNetUser"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRefreshTokenAspNetUser");

                    b.ToTable("RefreshTokenAspNetUser");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Season", b =>
                {
                    b.Property<int>("IdSeason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeason"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("int");

                    b.HasKey("IdSeason");

                    b.HasIndex("IdCompany");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GenericApp.Data.Models.State", b =>
                {
                    b.Property<int>("IdState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdState"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdState");

                    b.HasIndex("IdCountry");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            IdState = 1,
                            Description = "Aguascalientes",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 2,
                            Description = "Baja California",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 3,
                            Description = "Baja California Sur",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 4,
                            Description = "Campeche",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 5,
                            Description = "Coahuila",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 6,
                            Description = "Colima",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 7,
                            Description = "Chiapas",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 8,
                            Description = "Chihuahua",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 9,
                            Description = "Ciudad de México",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 10,
                            Description = "Durango",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 11,
                            Description = "Guanajuato",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 12,
                            Description = "Guerrero",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 13,
                            Description = "Hidalgo",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 14,
                            Description = "Jalisco",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 15,
                            Description = "Estado de México",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 16,
                            Description = "Michoacán",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 17,
                            Description = "Morelos",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 18,
                            Description = "Nayarit",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 19,
                            Description = "Nuevo León",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 20,
                            Description = "Oaxaca",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 21,
                            Description = "Puebla",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 22,
                            Description = "Querétaro",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 23,
                            Description = "Quintana Roo",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 24,
                            Description = "San Luis Potosí",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 25,
                            Description = "Sinaloa",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 26,
                            Description = "Sonora",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 27,
                            Description = "Tabasco",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 28,
                            Description = "Tamaulipas",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 29,
                            Description = "Tlaxcala",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 30,
                            Description = "Veracruz",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 31,
                            Description = "Yucatán",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 32,
                            Description = "Zacatecas",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 33,
                            Description = "Alabama",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 34,
                            Description = "Alaska",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 35,
                            Description = "Arizona",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 36,
                            Description = "Arkansas",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 37,
                            Description = "California",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 38,
                            Description = "Colorado",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 39,
                            Description = "Connecticut",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 40,
                            Description = "Delaware",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 41,
                            Description = "Florida",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 42,
                            Description = "Georgia",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 43,
                            Description = "Hawaii",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 44,
                            Description = "Idaho",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 45,
                            Description = "Illinois",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 46,
                            Description = "Indiana",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 47,
                            Description = "Iowa",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 48,
                            Description = "Kansas",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 49,
                            Description = "Kentucky",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 50,
                            Description = "Louisiana",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 51,
                            Description = "Maine",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 52,
                            Description = "Maryland",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 53,
                            Description = "Massachusetts",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 54,
                            Description = "Michigan",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 55,
                            Description = "Minnesota",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 56,
                            Description = "Mississippi",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 57,
                            Description = "Missouri",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 58,
                            Description = "Montana",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 59,
                            Description = "Nebraska",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 60,
                            Description = "Nevada",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 61,
                            Description = "New Hampshire",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 62,
                            Description = "New Jersey",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 63,
                            Description = "New Mexico",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 64,
                            Description = "New York",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 65,
                            Description = "North Carolina",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 66,
                            Description = "North Dakota",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 67,
                            Description = "Ohio",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 68,
                            Description = "Oklahoma",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 69,
                            Description = "Oregon",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 70,
                            Description = "Pennsylvania",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 71,
                            Description = "Rhode Island",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 72,
                            Description = "South Carolina",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 73,
                            Description = "South Dakota",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 74,
                            Description = "Tennessee",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 75,
                            Description = "Texas",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 76,
                            Description = "Utah",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 77,
                            Description = "Vermont",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 78,
                            Description = "Virginia",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 79,
                            Description = "Washington",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 80,
                            Description = "West Virginia",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 81,
                            Description = "Wisconsin",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 82,
                            Description = "Wyoming",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.UserDetail", b =>
                {
                    b.Property<int>("IdUserDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserDetail"), 1L, 1);

                    b.Property<int?>("IdCompany")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUserDetail");

                    b.ToTable("UserDetails");

                    b.HasData(
                        new
                        {
                            IdUserDetail = 1,
                            IdCompany = 1,
                            IdUser = "a18be9c0-aa65-4af8-bd17-00bd9344e577"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            Name = "MultiEmpresa",
                            NormalizedName = "MULTIEMPRESA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            Email = "admin",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEALEDyqJ68CNqjqz/kLoDldUIT9AnmnaviMYziv2vgjrfnpCJupqFRtHUeonDIuq1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ClaimType = "User",
                            ClaimValue = "1",
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9344e575"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GenericApp.Data.Models.City", b =>
                {
                    b.HasOne("GenericApp.Data.Models.State", "IdStateNavigation")
                        .WithMany("Cities")
                        .HasForeignKey("IdState")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdStateNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Client", b =>
                {
                    b.HasOne("GenericApp.Data.Models.City", "IdCityNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCityNavigation");

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Contract", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ContractTemplate", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ContractTemplateContractSign", b =>
                {
                    b.HasOne("GenericApp.Data.Models.ContractSign", "IdContractSignNavigation")
                        .WithMany()
                        .HasForeignKey("IdContractSign")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.ContractTemplate", "IdContractTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("IdContractTemplate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdContractSignNavigation");

                    b.Navigation("IdContractTemplateNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Employee", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeBeneficiarie", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.EmployeeRelationshipType", "IdEmployeeRelationshipTypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdEmployeeRelationshipType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdEmployeeNavigation");

                    b.Navigation("IdEmployeeRelationshipTypeNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeDependents", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("Dependents")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.EmployeeRelationshipType", "IdEmployeeRelationshipTypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdEmployeeRelationshipType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdEmployeeNavigation");

                    b.Navigation("IdEmployeeRelationshipTypeNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeEmergencyContact", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("EmployeeEmergencyContacts")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.EmployeeRelationshipType", "IdEmployeeRelationshipTypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdEmployeeRelationshipType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdEmployeeNavigation");

                    b.Navigation("IdEmployeeRelationshipTypeNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.EmployeeWorkInformation", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("EmployeeWorkInformations")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdEmployeeNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Season", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.State", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Country", "IdCountryNavigation")
                        .WithMany("States")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCountryNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenericApp.Data.Models.City", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Employee", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Dependents");

                    b.Navigation("EmployeeEmergencyContacts");

                    b.Navigation("EmployeeWorkInformations");
                });

            modelBuilder.Entity("GenericApp.Data.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
