// <auto-generated />
using System;
using GenericApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260111205951_AddChismografoManifestPallet")]
    partial class AddChismografoManifestPallet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GenericApp.Data.Models.ApplicationLog", b =>
                {
                    b.Property<int>("IdApplicationLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApplicationLog"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Details2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdAspNetUsers")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdDataAffected")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdApplicationLog");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("GenericApp.Data.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdState")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdCity");

                    b.HasIndex("IdState");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            IdCity = 1,
                            Description = "Tijuana",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 2,
                            Description = "Mexicali",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 3,
                            Description = "Ensenada",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 4,
                            Description = "Playas de Rosarito",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 5,
                            Description = "Tecate",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 6,
                            Description = "San Quintín",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 7,
                            Description = "San Felipe",
                            IdState = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 8,
                            Description = "Los Angeles",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 9,
                            Description = "San Diego",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 10,
                            Description = "San Jose",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCity = 11,
                            Description = "Calexico",
                            IdState = 37,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdClient");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdCompany");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Empaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GnnNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegFdaNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdCompany");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            IdCompany = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mision"
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCountry"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdCountry");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            IdCountry = 1,
                            Description = "México",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdCountry = 2,
                            Description = "Estados Unidos",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Driver", b =>
                {
                    b.Property<int>("IdDriver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDriver"), 1L, 1);

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdDriver");

                    b.HasIndex("IdCompany");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Label", b =>
                {
                    b.Property<int>("IdLabel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLabel"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxBoxQuantity")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdLabel");

                    b.HasIndex("IdCompany");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("GenericApp.Data.Models.LabelType", b =>
                {
                    b.Property<int>("IdLabelType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLabelType"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdLabel")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLabelType");

                    b.HasIndex("IdLabel");

                    b.ToTable("LabelTypes");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Manifest", b =>
                {
                    b.Property<int>("IdManifest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManifest"), 1L, 1);

                    b.Property<string>("Chismografo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Empaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GnnNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCompany")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("IdDriver")
                        .HasColumnType("int");

                    b.Property<int>("IdManifestStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdSeason")
                        .HasColumnType("int");

                    b.Property<int>("IdShipment")
                        .HasColumnType("int");

                    b.Property<int>("IdShippingCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RegFdaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stamps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TemperatureTrailerBoxC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TemperatureTrailerBoxF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerBoxPlate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrailerPlate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdManifest");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdDriver");

                    b.HasIndex("IdManifestStatus");

                    b.HasIndex("IdSeason");

                    b.HasIndex("IdShipment");

                    b.HasIndex("IdShippingCompany");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ManifestPallet", b =>
                {
                    b.Property<int>("IdManifestPallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManifestPallet"), 1L, 1);

                    b.Property<bool?>("Chismografo")
                        .HasColumnType("bit");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdLabel")
                        .HasColumnType("int");

                    b.Property<int>("IdManifest")
                        .HasColumnType("int");

                    b.Property<int?>("IdShipmentNavigationIdShipment")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxBoxQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TemperatureF")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdManifestPallet");

                    b.HasIndex("IdLabel");

                    b.HasIndex("IdManifest");

                    b.HasIndex("IdShipmentNavigationIdShipment");

                    b.ToTable("ManifestPallets");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ManifestPalletLoading", b =>
                {
                    b.Property<int>("IdManifestPalletLoading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManifestPalletLoading"), 1L, 1);

                    b.Property<decimal?>("BoxQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdLabelType")
                        .HasColumnType("int");

                    b.Property<int?>("IdManifestNavigationIdManifest")
                        .HasColumnType("int");

                    b.Property<int>("IdManifestPallet")
                        .HasColumnType("int");

                    b.Property<int?>("IdShipmentNavigationIdShipment")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdManifestPalletLoading");

                    b.HasIndex("IdLabelType");

                    b.HasIndex("IdManifestNavigationIdManifest");

                    b.HasIndex("IdManifestPallet");

                    b.HasIndex("IdShipmentNavigationIdShipment");

                    b.ToTable("ManifestPalletLoadings");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ManifestStatus", b =>
                {
                    b.Property<int>("IdManifestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManifestStatus"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdManifestStatus");

                    b.ToTable("ManifestStatuses");

                    b.HasData(
                        new
                        {
                            IdManifestStatus = 1,
                            Description = "Activa",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdManifestStatus = 2,
                            Description = "Concluída",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.Parameter", b =>
                {
                    b.Property<int>("IdParameter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParameter"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdParameter");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("GenericApp.Data.Models.RefreshTokenAspNetUser", b =>
                {
                    b.Property<int>("IdRefreshTokenAspNetUser")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefreshTokenAspNetUser"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("1");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdRefreshTokenAspNetUser");

                    b.ToTable("RefreshTokenAspNetUser");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Season", b =>
                {
                    b.Property<int>("IdSeason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeason"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("int");

                    b.HasKey("IdSeason");

                    b.HasIndex("IdCompany");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Shipment", b =>
                {
                    b.Property<int>("IdShipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdShipment"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdCompany")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("IdShipmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("Mixed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("date");

                    b.HasKey("IdShipment");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdShipmentStatus");

                    b.HasIndex("IdUser");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ShipmentStatus", b =>
                {
                    b.Property<int>("IdShipmentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdShipmentStatus"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdShipmentStatus");

                    b.ToTable("ShipmentStatuses");

                    b.HasData(
                        new
                        {
                            IdShipmentStatus = 1,
                            Description = "Activa",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdShipmentStatus = 2,
                            Description = "Concluída",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.ShippingCompany", b =>
                {
                    b.Property<int>("IdShippingCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdShippingCompany"), 1L, 1);

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdShippingCompany");

                    b.ToTable("ShippingCompanies");
                });

            modelBuilder.Entity("GenericApp.Data.Models.State", b =>
                {
                    b.Property<int>("IdState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdState"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdState");

                    b.HasIndex("IdCountry");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            IdState = 1,
                            Description = "Aguascalientes",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 2,
                            Description = "Baja California",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 3,
                            Description = "Baja California Sur",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 4,
                            Description = "Campeche",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 5,
                            Description = "Coahuila",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 6,
                            Description = "Colima",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 7,
                            Description = "Chiapas",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 8,
                            Description = "Chihuahua",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 9,
                            Description = "Ciudad de México",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 10,
                            Description = "Durango",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 11,
                            Description = "Guanajuato",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 12,
                            Description = "Guerrero",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 13,
                            Description = "Hidalgo",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 14,
                            Description = "Jalisco",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 15,
                            Description = "Estado de México",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 16,
                            Description = "Michoacán",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 17,
                            Description = "Morelos",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 18,
                            Description = "Nayarit",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 19,
                            Description = "Nuevo León",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 20,
                            Description = "Oaxaca",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 21,
                            Description = "Puebla",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 22,
                            Description = "Querétaro",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 23,
                            Description = "Quintana Roo",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 24,
                            Description = "San Luis Potosí",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 25,
                            Description = "Sinaloa",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 26,
                            Description = "Sonora",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 27,
                            Description = "Tabasco",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 28,
                            Description = "Tamaulipas",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 29,
                            Description = "Tlaxcala",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 30,
                            Description = "Veracruz",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 31,
                            Description = "Yucatán",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 32,
                            Description = "Zacatecas",
                            IdCountry = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 33,
                            Description = "Alabama",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 34,
                            Description = "Alaska",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 35,
                            Description = "Arizona",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 36,
                            Description = "Arkansas",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 37,
                            Description = "California",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 38,
                            Description = "Colorado",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 39,
                            Description = "Connecticut",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 40,
                            Description = "Delaware",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 41,
                            Description = "Florida",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 42,
                            Description = "Georgia",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 43,
                            Description = "Hawaii",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 44,
                            Description = "Idaho",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 45,
                            Description = "Illinois",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 46,
                            Description = "Indiana",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 47,
                            Description = "Iowa",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 48,
                            Description = "Kansas",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 49,
                            Description = "Kentucky",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 50,
                            Description = "Louisiana",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 51,
                            Description = "Maine",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 52,
                            Description = "Maryland",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 53,
                            Description = "Massachusetts",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 54,
                            Description = "Michigan",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 55,
                            Description = "Minnesota",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 56,
                            Description = "Mississippi",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 57,
                            Description = "Missouri",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 58,
                            Description = "Montana",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 59,
                            Description = "Nebraska",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 60,
                            Description = "Nevada",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 61,
                            Description = "New Hampshire",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 62,
                            Description = "New Jersey",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 63,
                            Description = "New Mexico",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 64,
                            Description = "New York",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 65,
                            Description = "North Carolina",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 66,
                            Description = "North Dakota",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 67,
                            Description = "Ohio",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 68,
                            Description = "Oklahoma",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 69,
                            Description = "Oregon",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 70,
                            Description = "Pennsylvania",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 71,
                            Description = "Rhode Island",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 72,
                            Description = "South Carolina",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 73,
                            Description = "South Dakota",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 74,
                            Description = "Tennessee",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 75,
                            Description = "Texas",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 76,
                            Description = "Utah",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 77,
                            Description = "Vermont",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 78,
                            Description = "Virginia",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 79,
                            Description = "Washington",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 80,
                            Description = "West Virginia",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 81,
                            Description = "Wisconsin",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            IdState = 82,
                            Description = "Wyoming",
                            IdCountry = 2,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("GenericApp.Data.Models.UserDetail", b =>
                {
                    b.Property<int>("IdUserDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserDetail"), 1L, 1);

                    b.Property<int?>("IdCompany")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUserDetail");

                    b.ToTable("UserDetails");

                    b.HasData(
                        new
                        {
                            IdUserDetail = 1,
                            IdCompany = 1,
                            IdUser = "a18be9c0-aa65-4af8-bd17-00bd9344e577"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e578",
                            Name = "MultiEmpresa",
                            NormalizedName = "MULTIEMPRESA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            Email = "admin",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEB5ABrZAt4J/Z0PDafsZ0IE071MdyWQfZMOS2E0qITEjtz3Jdc76NJB7FOprwtbTMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ClaimType = "User",
                            ClaimValue = "1",
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9344e575"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GenericApp.Data.Models.City", b =>
                {
                    b.HasOne("GenericApp.Data.Models.State", "IdStateNavigation")
                        .WithMany("Cities")
                        .HasForeignKey("IdState")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdStateNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Client", b =>
                {
                    b.HasOne("GenericApp.Data.Models.City", "IdCityNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCityNavigation");

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Driver", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Label", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.LabelType", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Label", "IdLabelNavigation")
                        .WithMany("LabelTypes")
                        .HasForeignKey("IdLabel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdLabelNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Manifest", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Driver", "IdDriverNavigation")
                        .WithMany()
                        .HasForeignKey("IdDriver")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.ManifestStatus", "IdManifestStatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdManifestStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Season", "IdSeasonNavigation")
                        .WithMany()
                        .HasForeignKey("IdSeason")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Shipment", "IdShipmentNavigation")
                        .WithMany("Manifests")
                        .HasForeignKey("IdShipment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.ShippingCompany", "IdShippingCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdShippingCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");

                    b.Navigation("IdDriverNavigation");

                    b.Navigation("IdManifestStatusNavigation");

                    b.Navigation("IdSeasonNavigation");

                    b.Navigation("IdShipmentNavigation");

                    b.Navigation("IdShippingCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ManifestPallet", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Label", "IdLabelNavigation")
                        .WithMany()
                        .HasForeignKey("IdLabel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Manifest", "IdManifestNavigation")
                        .WithMany("ManifestPallets")
                        .HasForeignKey("IdManifest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Shipment", "IdShipmentNavigation")
                        .WithMany()
                        .HasForeignKey("IdShipmentNavigationIdShipment");

                    b.Navigation("IdLabelNavigation");

                    b.Navigation("IdManifestNavigation");

                    b.Navigation("IdShipmentNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ManifestPalletLoading", b =>
                {
                    b.HasOne("GenericApp.Data.Models.LabelType", "IdLabelTypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdLabelType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Manifest", "IdManifestNavigation")
                        .WithMany()
                        .HasForeignKey("IdManifestNavigationIdManifest");

                    b.HasOne("GenericApp.Data.Models.ManifestPallet", "IdManifestPalletNavigation")
                        .WithMany("ManifestPalletLoadings")
                        .HasForeignKey("IdManifestPallet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Shipment", "IdShipmentNavigation")
                        .WithMany()
                        .HasForeignKey("IdShipmentNavigationIdShipment");

                    b.Navigation("IdLabelTypeNavigation");

                    b.Navigation("IdManifestNavigation");

                    b.Navigation("IdManifestPalletNavigation");

                    b.Navigation("IdShipmentNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Season", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompanyNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Shipment", b =>
                {
                    b.HasOne("GenericApp.Data.Models.City", "IdCityNavigation")
                        .WithMany()
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenericApp.Data.Models.Client", "IdClientNavigation")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.Company", "IdCompanyNavigation")
                        .WithMany()
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenericApp.Data.Models.ShipmentStatus", "IdShipmentStatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdShipmentStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdCityNavigation");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCompanyNavigation");

                    b.Navigation("IdShipmentStatusNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("GenericApp.Data.Models.State", b =>
                {
                    b.HasOne("GenericApp.Data.Models.Country", "IdCountryNavigation")
                        .WithMany("States")
                        .HasForeignKey("IdCountry")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCountryNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenericApp.Data.Models.City", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Label", b =>
                {
                    b.Navigation("LabelTypes");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Manifest", b =>
                {
                    b.Navigation("ManifestPallets");
                });

            modelBuilder.Entity("GenericApp.Data.Models.ManifestPallet", b =>
                {
                    b.Navigation("ManifestPalletLoadings");
                });

            modelBuilder.Entity("GenericApp.Data.Models.Shipment", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("GenericApp.Data.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
